### ISSUE TITLE
死锁

### ISSUE THREAD

**Issue by GoodManWEN** [ydf0509/threadpool_executor_shrink_able#1]
你好，我在异步封装的过程中用到线程池，搜索资料时发现了你的库，很有启发。

我按照你的思路在原生库的基础上实现了一份，但实现过程中我觉得有一个问题是 [这个位置](https://github.com/ydf0509/threadpool_executor_shrink_able/blob/ae07001f48b94717aee9d2b3f23970e58bc2e346/threadpool_executor_shrink_able/sharp_threadpoolexecutor.py#L137) ，当队列已经超时跳出后，程序不会随即减少可用的线程数量，也即默认状态下管理器认为该线程还是可用状态。这个时候如果刚好线程切换，且有一个新任务进入，此时管理器认为尚有空闲线程，不需要创建新线程，这种情况下，如果当时恰好已经没有活动线程，则会导致死锁。

简单想了一下没想到怎么解决。

**Comment by ydf0509** [comment]
从没发生死锁，这已经在生产实践两年了，也是分布式函数调度框架的默认并发池，不会出现死锁。没有一个所谓的什么管理器认为线程是不是可用状态，任何线程池无非就是固定数量的线程里面跑 while 1的函数，然后while 1 里面不停的从queue队列get 一个要执行的 函数名和参数，然后去运行函数，kepp alivetime参数是如果60秒都没get到函数和参数，就break while 1线程也就结束了。没有所谓的管理器这种东西。你直接用我的这个就行了，不要自己在原生库实现什么东西。

**Comment by GoodManWEN** [comment]
口气可以。我不是说我的实现有问题，我是说你的实现有问题。能看懂你写的代码，你能看懂我写的回复吗？

当子线程中线程超时触发异常后，executor.threads_free_count 不会立即释放，此时如果主线程恰好引入新任务，调用 _adjust_thread_count ， 那么会认为尚有空闲线程，不满足创建新线程的条件，导致任务添加到队列，但没有woker执行。

生产实践两年也是逗，小概率发生不代表不发生，你要不然说服我逻辑错了，要不然就修BUG。赌不发生小概率事件，不如干脆不加线程锁。

**Comment by ydf0509** [comment]
当子线程中发生错误？没这种可能性，你看第52行，
try:
         self.fn(*self.args, **self.kwargs)
except BaseException as exc:
         self.logger.exception(f'函数 {self.fn.__name__} 中发生错误，错误原因是 {type(exc)} {exc} ')
请问捕获了BaseException 什么错误还能够抛出来？实际跑的是try 包装的函数，不是直接跑函数本身，没出错这种可能，用这个线程池你可以写个例子出来，演示这个可能性。你def f(): 1/0，就觉子线程会出错吗。

**Comment by GoodManWEN** [comment]
驴唇不对马嘴，这个repo真的是你写的吗？

**Comment by lypro09539** [comment]
> 从没发生死锁，这已经在生产实践两年了，也是分布式函数调度框架的默认并发池，不会出现死锁。没有一个所谓的什么管理器认为线程是不是可用状态，任何线程池无非就是固定数量的线程里面跑 while 1的函数，然后while 1 里面不停的从queue队列get 一个要执行的 函数名和参数，然后去运行函数，kepp alivetime参数是如果60秒都没get到函数和参数，就break while 1线程也就结束了。没有所谓的管理器这种东西。你直接用我的这个就行了，不要自己在原生库实现什么东西。

他的意思是 您的线程收缩时逻辑是先判断数量关系 再加锁改值，这中间有时间差：（数字代表发生顺序）

0. 多个线程一起判断当前线程数，结论全是要结束自己，进入if逻辑代码块（此时发生线程调度，执行主线程）
0.  主线程submit新任务，adjust_thread_count，判断线程数，结论是不需要新建线程（该结论错误）
1.  多个线程各自结束自己，不会保持min_worker数量。
2. 再也没有线程去取任务执行了。

@GoodManWEN 这个老哥说的这种情况是可以人为模拟出来的，我本地加sleep模拟的。线上概率为0，但是是可能事件。

**Comment by ydf0509** [comment]
> > 从没发生死锁，这已经在生产实践两年了，也是分布式函数调度框架的默认并发池，不会出现死锁。没有一个所谓的什么管理器认为线程是不是可用状态，任何线程池无非就是固定数量的线程里面跑 while 1的函数，然后while 1 里面不停的从queue队列get 一个要执行的 函数名和参数，然后去运行函数，kepp alivetime参数是如果60秒都没get到函数和参数，就break while 1线程也就结束了。没有所谓的管理器这种东西。你直接用我的这个就行了，不要自己在原生库实现什么东西。
> 
> 他的意思是 您的线程收缩时逻辑是先判断数量关系 再加锁改值，这中间有时间差：（数字代表发生顺序）
> 
> 1. 多个线程一起判断当前线程数，结论全是要结束自己，进入if逻辑代码块（此时发生线程调度，执行主线程）
> 2. 主线程submit新任务，adjust_thread_count，判断线程数，结论是不需要新建线程（该结论错误）
> 3. 多个线程各自结束自己，不会保持min_worker数量。
> 4. 再也没有线程去取任务执行了。
> 
> @GoodManWEN 这个老哥说的这种情况是可以人为模拟出来的，我本地加sleep模拟的。线上概率为0，但是是可能事件。

你说得好。

 if self._executorx.threads_free_count > self._executorx._min_workers:
                    self._remove_thread(f'当前线程超过60秒没有任务，线程池中不在工作状态中的线程数量是 {self._executorx.threads_free_count}，超过了指定的数量 {self._executorx._min_workers}')
                    break

在if的外层加一个锁

    with self._executorx._lock_compute_threads_free_count:
                    if self._executorx.threads_free_count > self._executorx._min_workers:
                        self._remove_thread(f'当前线程超过60秒没有任务，线程池中不在工作状态中的线程数量是 {self._executorx.threads_free_count}，超过了指定的数量 {self._executorx._min_workers}')
                        break   # 退出while 1，即是结束。这里才是决定线程结束销毁，_remove_thread只是个名字而已，不是由那个来销毁线程。
                    else:
                        continue
这怎么样。


你本地sleep模拟，submit停一段时间，突然submit，以后的函数任务永久不被执行了吗。这个不会吧，在change_tread那有锁，减少了多少线程 增加了多少线程都严格加锁了。

**Comment by Fre-ak** [comment]
https://www.v2ex.com/t/739455

**Comment by lypro09539** [comment]
@ydf0509 
把remove_thread的锁提到if外层确实可以。

另外也可以加个核心线程的概念，数量等于min_workers，也不会死亡，对其不设置超时时间（或者空闲超时后直接continue）。这样的话也可以避免该issue的问题。

关于你的疑问：我模拟的就是上述步骤描述的，确实会出现任务永远不执行。就是用sleep几秒去模拟上文描述的调度顺序。

**Comment by GoodManWEN** [comment]
@lypro09539 
核心线程的想法很好，开阔了思路，可以从根本上解决目前无法完全解决的死锁的问题。虽然仍有极小概率全部线程被占用，导致任务阻塞，但似乎已经是目前最好的解决方案，只是具体实现上还要琢磨琢磨。

因为线程的time slicing完全归系统调度，实际模拟出这种特殊情况比较难，我没有写代码，如果你有可以复现的代码欢迎发出来看一下。概念上可以设例是（与上文所提不同的另外一种bug），假如按照目前实现，在读取 threads_free_count 的过程中不加锁，在修改threads_free_count的过程中加锁，那么有可能导致

更新threads_free_count的byte code是
```
0 LOAD_FAST                0 (threads_free_count)
2 LOAD_CONST               1 (1)
4 INPLACE_ADD
6 STORE_FAST               0 (threads_free_count)
```
即使加锁，其中执行到LOAD_CONST中断，线程切换到读取 threads_free_count
```
0 LOAD_GLOBAL              0 (self)
2 LOAD_ATTR                1 (_threads_free_count)
4 LOAD_GLOBAL              2 (self)
6 LOAD_ATTR                1 (_min_workers)
8 COMPARE_OP               4 (>)
10 POP_JUMP_IF_FALSE       12
```
计数仍以未更新状态进行判断，可能导致线程数量估算大于实际值，阻止其正常的摧毁操作。

说实话作者说这个库生产环境运行两年0bug我觉得运气挺好的。

**Comment by ydf0509** [comment]
> @lypro09539
> 核心线程的想法很好，开阔了思路，可以从根本上解决目前无法完全解决的死锁的问题。虽然仍有极小概率全部线程被占用，导致任务阻塞，但似乎已经是目前最好的解决方案，只是具体实现上还要琢磨琢磨。
> 
> 因为线程的time slicing完全归系统调度，实际模拟出这种特殊情况比较难，我没有写代码，如果你有可以复现的代码欢迎发出来看一下。概念上可以设例是（与上文所提不同的另外一种bug），假如按照目前实现，在读取 threads_free_count 的过程中不加锁，在修改threads_free_count的过程中加锁，那么有可能导致
> 
> 更新threads_free_count的byte code是
> 
> ```
> 0 LOAD_FAST                0 (threads_free_count)
> 2 LOAD_CONST               1 (1)
> 4 INPLACE_ADD
> 6 STORE_FAST               0 (threads_free_count)
> ```
> 
> 即使加锁，其中执行到LOAD_CONST中断，线程切换到读取 threads_free_count
> 
> ```
> 0 LOAD_GLOBAL              0 (self)
> 2 LOAD_ATTR                1 (_threads_free_count)
> 4 LOAD_GLOBAL              2 (self)
> 6 LOAD_ATTR                1 (_min_workers)
> 8 COMPARE_OP               4 (>)
> 10 POP_JUMP_IF_FALSE       12
> ```
> 
> 计数仍以未更新状态进行判断，可能导致线程数量估算大于实际值，阻止其正常的摧毁操作。
> 
> 说实话作者说这个库生产环境运行两年0bug我觉得运气挺好的。

经常函数老虎固定sleep n秒，推送一批任务，一般是放在分布式函数调度框架一起测的，线程方式比较好用，gevent  eventlet都一套加猴子补丁，asyncio需要大改特改，一般都是用这个协程池测的分布式并发调度。

**Comment by GoodManWEN** [comment]
@lypro09539 @ydf0509 [做了个实现](https://github.com/GoodManWEN/ThreadPoolExecutorPlus/blob/19404ba8c141d802b75bb6446730dfa6ec4bd923/ThreadPoolExecutorPlus/thread.py#L110)
